apiVersion: v1
kind: ConfigMap
metadata:
  name: maps-app-config
data:
  # The URL uses "mysql" as the hostname, which is the name of the K8s Service for MySQL.
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/maps_project_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
