spring.application.name=maps

# Server Port (optional, default is 8080)
server.port=8080


# Timeout per le chiamate API 
# (usato da Resilience4j TimeLimiter)
# API Timeout (in seconds)
# api.timeout.seconds=10
app.api.timeout.seconds=10

# Endpoint Base directions
# URL dell'API Directions di Google
app.google.directions.api.url=https://maps.googleapis.com/maps/api/directions/json
# percorso di Default (coordinate origin e destination)
app.traffic.route.origin=37.5289035,15.1132497
# 37.5289035	15.1132497
# ognina
app.traffic.route.destination=37.5242754,15.0710061
# cittadella universitaria catania
# 	37.5242754	15.0710061

# Traffic Collection Scheduling
traffic.collection.fixedDelayMs=600000
# Intervallo di raccolta: ogni 10 minuti (600,000 ms)

# Google Maps API Key
google.maps.api.key=${GOOGLE_MAPS_API_KEY}


# Configurazione del Database (MySQL)
# jdbc:mysql://localhost:3306/maps_project_db
spring.datasource.url=jdbc:mysql://localhost:3306/maps_project_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.connection-timeout=300000 
# 300 secondi (5 minuti)
# valore alto per test
spring.datasource.hikari.maximum-pool-size=10 
# non troppo basso o troppo alto

# Configurazione JPA/Hibernate 
spring.jpa.hibernate.ddl-auto=update
# update / create / validate
# "update" per aggiornare lo schema, "create" per ricrearlo ad ogni avvio
# 'validate' in produzione
spring.jpa.show-sql=true
# Mostra le query SQL nella console
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect






# Resilience4j Configurations
resilience4j.circuitbreaker.instances.googleApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.googleApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.googleApi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.googleApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.googleApi.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.googleApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.retry.instances.googleApi.maxAttempts=3
resilience4j.retry.instances.googleApi.waitDuration=2s
resilience4j.retry.instances.googleApi.retryExceptions=java.util.concurrent.TimeoutException,org.springframework.web.client.ResourceAccessException
resilience4j.timelimiter.instances.googleApi.timeoutDuration=5s
resilience4j.timelimiter.instances.googleApi.cancelRunningFuture=true



# Logging
logging.level.com.example.datacollector=INFO
logging.file.name=traffic_collector.log

# Actuator Health Probes (per Kubernetes)
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus