#!/bin/bash
set -e

# Passing optional parameters (e.g. ./deploy_k3s_linux.sh "mypass" "myapikey")
DB_PASSWORD=${1:-"PASS"}
GOOGLE_API_KEY=${2:-"API_KEY"}

echo "=========================================="
echo "🚀 STARTING AWS CLOUD DEPLOYMENT (LINUX/MAC) 🚀"
echo "=========================================="

echo -e "\n1️⃣ Starting Terraform (Infrastructure, RDS, EC2, ALB creation)..."
# [1 - TERRAFORM APPLY] Launches Infrastructure as Code on AWS.
cd aws-terraform
terraform init
terraform apply -var="db_password=$DB_PASSWORD" -var="google_api_key=$GOOGLE_API_KEY" -auto-approve

echo -e "\n2️⃣ Retrieving public IPs generated by Terraform..."
MASTER_IP=$(terraform output -raw k3s_master_ip)
WORKER_IP=$(terraform output -raw k3s_worker_ip)
ALB_DNS=$(terraform output -raw alb_dns_name)
cd ..

echo "Master IP found: $MASTER_IP"
echo "Worker IP found: $WORKER_IP"
echo "ALB URL: $ALB_DNS"

echo -e "\n3️⃣ Waiting 30 seconds for EC2 machines to start..."
sleep 30

echo -e "\n4️⃣ Installing K3s via Ansible..."
# [2 - CONFIGURATION MANAGEMENT] Unlike Windows, on Mac/Linux we use Ansible natively
# Ansible will read the inventory generated by Terraform, install the master, and join the worker automatically.

export ANSIBLE_HOST_KEY_CHECKING=False # Prevents confirmation prompt for unknown hosts
chmod 600 ansible/k3s-key.pem # Mac/Linux require strict permissions for the private key

ansible-playbook -i ansible/inventory.ini ansible/playbook-k3s.yml --private-key ansible/k3s-key.pem -u ubuntu

echo -e "\n5️⃣ Deploying Kubernetes Manifests (Database and App)..."
# [3 - KUBERNETES SECRETS & DEPLOY] Generates a temporary ECR token from AWS
# and injects it into K8s as a 'Secret' (ecr-registry-secret) for pulling the image.
echo "Requesting Docker password from AWS ECR..."
ECR_PASSWORD=$(aws ecr get-login-password --region eu-west-1)

echo "Applying secrets on K3s..."
ssh -o StrictHostKeyChecking=no -i ansible/k3s-key.pem ubuntu@$MASTER_IP "sudo k3s kubectl create secret docker-registry ecr-registry-secret --docker-server=493789587491.dkr.ecr.eu-west-1.amazonaws.com --docker-username=AWS --docker-password=$ECR_PASSWORD --dry-run=client -o yaml | sudo k3s kubectl apply -f -"

# Creates a local copy to inject the ECR tag and secrets
cp -r k8s temp_k8s

# sed compatibility for Mac (BSD) and Linux (GNU)
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' 's/imagePullPolicy: IfNotPresent/imagePullPolicy: Always\n        imagePullSecrets:\n        - name: ecr-registry-secret/g' temp_k8s/app-deployment.yaml
  sed -i '' 's|image: maps-app:latest|image: 493789587491.dkr.ecr.eu-west-1.amazonaws.com/maps-app-repo:latest|g' temp_k8s/app-deployment.yaml
else
  sed -i 's/imagePullPolicy: IfNotPresent/imagePullPolicy: Always\n        imagePullSecrets:\n        - name: ecr-registry-secret/g' temp_k8s/app-deployment.yaml
  sed -i 's|image: maps-app:latest|image: 493789587491.dkr.ecr.eu-west-1.amazonaws.com/maps-app-repo:latest|g' temp_k8s/app-deployment.yaml
fi

echo "Copying YAML files to the Master..."
scp -o StrictHostKeyChecking=no -i ansible/k3s-key.pem -r temp_k8s ubuntu@$MASTER_IP:~/

echo "Applying Kubernetes..."
ssh -o StrictHostKeyChecking=no -i ansible/k3s-key.pem ubuntu@$MASTER_IP "sudo k3s kubectl apply -f ~/temp_k8s/"

# Cleanup temporary files
rm -rf temp_k8s

echo -e "\n🎉 CLOUD DEPLOYMENT COMPLETED! 🎉"
echo "The application will be reachable in a few minutes at the following address:"
echo "👉 http://$ALB_DNS/graphql"
echo "note: Remember to run 'cd aws-terraform && terraform destroy' when done!"

# cd infrastructure
# chmod +x deploy_k3s_linux.sh
# ./deploy_k3s_linux.sh "YourDBPassword" "YourGoogleApiKey"
