param (
    [string]$DbPassword = "PASS",
    [string]$GoogleApiKey = "API_KEY"
)

Write-Host "=========================================="
Write-Host "[STARTING AWS CLOUD DEPLOYMENT]"
Write-Host "=========================================="

Write-Host "`n[1] Starting Terraform (Infrastructure, RDS, EC2, ALB creation)..."
# [1 - TERRAFORM APPLY] Launches Infrastructure as Code. Terraform physically creates the hardware on AWS.
# The 'DbPassword' and 'GoogleApiKey' input parameters are passed securely as variables.
Set-Location aws-terraform
terraform init
terraform apply -var="db_password=$DbPassword" -var="google_api_key=$GoogleApiKey" -auto-approve

if ($LASTEXITCODE -ne 0) {
    Write-Host "[X] Error during Terraform apply!" -ForegroundColor Red
    exit
}

Write-Host "`n[2] Retrieving public IPs generated by Terraform..."
$MasterIP = (terraform output -raw k3s_master_ip)
$WorkerIP = (terraform output -raw k3s_worker_ip)
$AlbDns = (terraform output -raw alb_dns_name)
Set-Location ..

Write-Host "Master IP found: $MasterIP"
Write-Host "Worker IP found: $WorkerIP"
Write-Host "ALB URL: $AlbDns"

Write-Host "`n[3] Waiting 30 seconds to ensure machines are ready for SSH..."
Start-Sleep -Seconds 30

Write-Host "`n[4] Installing K3s on the MASTER NODE..."
# [2 - CONFIGURATION MANAGEMENT] Replaces Ansible. Downloads and installs
# K3s (Kubernetes) on the master node, configuring the bare Ubuntu machine via SSH.
$SshKey = "ansible\k3s-key.pem"

# Master SSH Command
$InstallMasterCmd = "LOCAL_IP=`$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4); export INSTALL_K3S_EXEC=\`"--tls-san $MasterIP --node-external-ip $MasterIP --node-ip `$LOCAL_IP --advertise-address `$LOCAL_IP\`"; curl -sfL https://get.k3s.io | sh -"
cmd.exe /c "ssh -o StrictHostKeyChecking=no -i $SshKey ubuntu@$MasterIP `"$InstallMasterCmd`""

Write-Host "`n[5] Retrieving Token from the Master to allow the Worker to join..."
# Extracts the cryptographic token file generated by the K3s Master needed to authorize workers.
$K3sToken = cmd.exe /c "ssh -o StrictHostKeyChecking=no -i $SshKey ubuntu@$MasterIP `"sudo cat /var/lib/rancher/k3s/server/node-token`""

Write-Host "Token successfully retrieved."

Write-Host "`n[6] Installing K3s on the WORKER NODE..."
# Uses the retrieved token to tell the Worker to join the main K3s cluster.
$InstallWorkerCmd = "curl -sfL https://get.k3s.io | K3S_URL=https://${MasterIP}:6443 K3S_TOKEN=$K3sToken sh -"
cmd.exe /c "ssh -o StrictHostKeyChecking=no -i $SshKey ubuntu@$WorkerIP `"$InstallWorkerCmd`""

Write-Host "`n[!] Waiting 20 seconds for the Kubernetes API to fully start..."
Start-Sleep -Seconds 20

Write-Host "`n[7] Deploying Kubernetes Manifests (Database and App)..."
# [3 - KUBERNETES SECRETS & DEPLOY] Authenticates K8s against the private Docker registry.
# Fetches a temporary ECR token from AWS and injects it into K8s as a 'Secret' (ecr-registry-secret).
# This is mandatory, otherwise K8s will not have permission to pull your Docker image.
# Generating the ECR token
Write-Host "Requesting Docker password from AWS ECR..."
$EcrPassword = (aws ecr get-login-password --region eu-west-1)

# Creating the temporary yaml file
Write-Host "Applying deployments..."
cmd.exe /c "ssh -o StrictHostKeyChecking=no -i $SshKey ubuntu@$MasterIP `"sudo k3s kubectl create secret docker-registry ecr-registry-secret --docker-server=493789587491.dkr.ecr.eu-west-1.amazonaws.com --docker-username=AWS --docker-password=$EcrPassword --dry-run=client -o yaml | sudo k3s kubectl apply -f -`""

# Applying the k8s folder files by sending them via cat (replaced with local copy)
Copy-Item "k8s" -Destination "temp_k8s" -Recurse -Force
# Patch for imagePullSecrets on the deployment
$DeployPath = "temp_k8s\app-deployment.yaml"
$Content = Get-Content $DeployPath
$Content = $Content -replace 'imagePullPolicy: IfNotPresent', 'imagePullPolicy: Always'
$Content = $Content -replace '      containers:', "      imagePullSecrets:`n        - name: ecr-registry-secret`n      containers:"
$Content = $Content -replace 'image: maps-app:latest', "image: 493789587491.dkr.ecr.eu-west-1.amazonaws.com/maps-app-repo:latest"
Set-Content -Path $DeployPath -Value $Content

# Patch for mysql-secret.yaml (injecting credentials passed to the script)
$SecretPath = "temp_k8s\mysql-secret.yaml"
$SecretContent = Get-Content $SecretPath
$DbBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($DbPassword))
$ApiBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($GoogleApiKey))
$SecretContent = $SecretContent -replace 'MYSQL_PASSWORD: .*', "MYSQL_PASSWORD: $DbBase64"
$SecretContent = $SecretContent -replace 'MYSQL_ROOT_PASSWORD: .*', "MYSQL_ROOT_PASSWORD: $DbBase64"
$SecretContent = $SecretContent -replace 'GOOGLE_MAPS_API_KEY: .*', "GOOGLE_MAPS_API_KEY: $ApiBase64"
Set-Content -Path $SecretPath -Value $SecretContent

Write-Host "Copying YAML files to the Master..."
cmd.exe /c "scp -o StrictHostKeyChecking=no -i $SshKey -r temp_k8s ubuntu@${MasterIP}:~/"

Write-Host "Applying Kubernetes..."
cmd.exe /c "ssh -o StrictHostKeyChecking=no -i $SshKey ubuntu@$MasterIP `"sudo k3s kubectl apply -f ~/temp_k8s/`""

Remove-Item "temp_k8s" -Recurse -Force

Write-Host "Forcing application restart to reload the new API Key..."
cmd.exe /c "ssh -o StrictHostKeyChecking=no -i $SshKey ubuntu@$MasterIP `"sudo k3s kubectl rollout restart deployment maps-app`""

Write-Host "`n*** CLOUD DEPLOYMENT COMPLETED! ***"
Write-Host "The application will be reachable in a few minutes at the following address:"
Write-Host "-> http://${AlbDns}/graphql"
Write-Host "NOTE: Remember to run `terraform destroy` when done!"
